### ISSUE TITLE
CDoc plugin requires that subroutine arguments are typed even though CCL does not

### ISSUE THREAD

**Issue by cernertrevor** [cerner/ccl-testing#28]
Currently, it is valid CCL to not declare a type on subroutine parameters.  See: https://wiki.cerner.com/display/public/1101discernHP/SUBROUTINE+Using+Discern+Explorer

`param_name [= datatype[(REF | VALUE[,param_default])]]`

This allows CCL to be dynamically typed.  Observe the below listing (which includes the program):

```
1)drop program tartest_1:group1 go
1)create program tartest_1:group1
2)
3)subroutine (testArgumentBug(argument) = null)
4)	call echo(reflect(argument))
5)	call echo(argument)
6)end
7)
8)call testArgumentBug(1)
9)call testArgumentBug("first")
10)
11)end
12)go
1)
1)execute tartest_1:group1 go
I4
1
C5
first
```

# Command run
mvn clean site -Psolm64
# Line in question:
https://github.com/cerner/ccl-testing/blob/db78c3efef32829b1ce4d5dcd4e500892db349be/cdoc/cdoc-parser/src/main/java/com/cerner/ccl/parser/text/subroutine/SubroutineDeclarationParser.java#L66
# Error Message:
[INFO] --- maven-site-plugin:3.7.1:site (default-site) @ ccl-unit-template ---
[INFO] configuring report plugin com.cerner.ccl.cdoc:cdoc-maven-plugin:1.2
[info] entering CDocReportMojo constructor
[INFO] 1 report detected for cdoc-maven-plugin:1.2: cdoc-report
[INFO] configuring report plugin com.cerner.ccl.testing:cerreal-maven-plugin:2.1
[INFO] 2 reports detected for cerreal-maven-plugin:2.1: coverage-report, test-report
[INFO] configuring report plugin com.cerner.ccl.whitenoise:whitenoise-maven-plugin:2.3
[INFO] 1 report detected for whitenoise-maven-plugin:2.3: whitenoise-report
[INFO] configuring report plugin org.apache.maven.plugins:maven-project-info-reports-plugin:3.0.0
[INFO] 15 reports detected for maven-project-info-reports-plugin:3.0.0: ci-management, dependencies, dependency-info, dependency-management, distribution-management, index, issue-management, licenses, mailing-lists, modules, plugin-management, plugins, scm, summary, team
[INFO] Cannot generate CCL Coverage report due to missing test-results directory
[INFO] Cannot generate Cerreal report due to missing test-results directory
[INFO] Rendering site with default locale English (en)
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering content with org.apache.maven.skins:maven-default-skin:jar:1.2 skin.
[INFO] Generating "CDoc" report          --- cdoc-maven-plugin:1.2:cdoc-report
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.133 s
[INFO] Finished at: 2019-05-20T15:39:24-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.7.1:site (default-site) on project ccl-unit-template: Error generating cdoc-maven-plugin:1.2:cdoc-report report: Failed to parse script tartest_1.prg: Invalid argument definition: argument -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
# CCL Unit Framework Version
3.3
# Target folder
[target.zip](https://github.com/cerner/ccl-testing/files/3199779/target.zip)
# Expected Output
Ideally, since it seems CCL can actually support dynamic typing, I would expect that the CDoc plugin could handle that and either display it as such or not display the type at all.  If we want to encourage people _not_ to do this, then I think it should be a Whitenoise rule, and CDoc should still succeed.  

What I don't think should happen is for CDoc to fail even when the CCL is valid, can be compiled in the domain, and run without error.

**Comment by feckertson** [comment]
Fixed by #54
